import java.awt.Dimension;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * sales.java
 *
 * Created on Jul 15, 2013, 10:04:07 AM
 */
/**
 *
 * @author DELL
 */
public class accessoriessales extends javax.swing.JFrame {
    int i,y;
JLabel []l1=new JLabel[100]; 
	JLabel []l2=new JLabel[100]; 
	JLabel []l3=new JLabel[100]; 
	JLabel []l4=new JLabel[100]; 

    /** Creates new form sales */
    public accessoriessales() {
        setPreferredSize( new Dimension(750,700));
        initComponents();
        try
		{
		Class.forName("com.mysql.jdbc.Driver");
		Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
		ResultSet rs=con.createStatement().executeQuery("select distinct(date) from regorder_acc");
                while (rs.next())
			{
				jComboBox1.addItem(rs.getString(1));
			}}
        catch(Exception ex){
                            }

	
		
               
	      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "%" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(182, 14, 103, 20);

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(349, 14, 120, 23);

        jLabel1.setText("CUSTOMER NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(34, 92, 104, 25);

        jLabel2.setText("ACCESSORIES");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(172, 88, 103, 32);

        jLabel3.setText("TOTAL AMOUNT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(293, 93, 110, 23);

        jLabel4.setText("DATE OF ORDER REGISTRATION");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(415, 88, 210, 33);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\New folder\\images (14)ml;t.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(540, 350, 230, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
    {
		Class.forName("com.mysql.jdbc.Driver");
		Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");	
 ResultSet rs=con.createStatement().executeQuery("select * from regorder_acc where date='"+jComboBox1.getSelectedItem()+"'");
 while(rs.next()){
				
					
					l1[i] = new JLabel();
					l1[i].setText("");
					l1[i].setText(rs.getString(1));
					getContentPane().add(l1[i]);
					l1[i].setBounds(50,y,120,250);
					
					l2[i] = new JLabel();
					l2[i].setText("");
					l2[i].setText(rs.getString(2));
					getContentPane().add(l2[i]);
					l2[i].setBounds(200,y,130,250);
					
					
					l3[i] = new JLabel();
					l3[i].setText(rs.getString(3));
					getContentPane().add(l3[i]);
					l3[i].setBounds(320,y,130,250);
									
					l4[i] = new JLabel();
					l4[i].setText(rs.getString(4));
					getContentPane().add(l4[i]);
					l4[i].setBounds(455,y,230,250);
				y=y+20;
 
				}
                        }
                
                catch(Exception ex)
		{
                }// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accessoriessales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accessoriessales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accessoriessales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accessoriessales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new accessoriessales().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
