import java.awt.Dimension;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.regex.Pattern;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ACCUPADATION.java
 *
 * Created on Jul 10, 2013, 5:58:48 PM
 */
/**
 *
 * @author DELL
 */
public class ACCUPADATION extends javax.swing.JFrame {

    /** Creates new form ACCUPADATION */
    public ACCUPADATION() {
        setPreferredSize(new Dimension(500,450));
        initComponents();
        try{
        Class.forName("com.mysql.jdbc.Driver");

Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
        ResultSet rs=con.createStatement().executeQuery("select accessories from acc_reg");
        while(rs.next()){
            jComboBox1.addItem(rs.getString(1));
        }}catch(Exception ex){
            
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EDIT/VIEW");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("ACCESSORY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 60, 90, 14);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(197, 56, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("COST");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 130, 50, 14);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(197, 138, 170, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(63, 330, 90, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 330, 90, 23);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(260, 330, 80, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton4.setText("CANCEL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(350, 330, 90, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("DESCRIPTION");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 230, 90, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(197, 216, 180, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\images (2).jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-30, 0, 550, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//TODO add your handling code here:
    try{
    Class.forName("com.mysql.jdbc.Driver");

Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
con.createStatement().executeUpdate("update acc_reg set cost ='"+jTextField1.getText()+"',description='"+jTextArea1.getText()+"' where accessories='"+jComboBox1.getSelectedItem()+"'"); 
// TODO add your handling code here:
JOptionPane.showMessageDialog(this,"Records updated");
this.dispose();
}catch(Exception ex){}// TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.dispose();
// TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
    Class.forName("com.mysql.jdbc.Driver");

Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
ResultSet rs=con.createStatement().executeQuery("select * from acc_reg where accessories='"+jComboBox1.getSelectedItem()+"'");
while(rs.next()){
    String s1=rs.getString(2);
    jTextField1.setText(s1);
    String s2=rs.getString(3);
    jTextArea1.setText(s2);
    
}
}catch(Exception ex){}// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try
{
Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
con.createStatement().executeUpdate("delete from acc_reg where accessories='"+jComboBox1.getSelectedItem()+"'");
JOptionPane.showMessageDialog(this,"Record Deleted successfully");
        this.dispose();
} 
catch(Exception e)
{
System.out.print(e);
}// TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
String k4=jTextField1.getText();
if(k4.isEmpty())
{
    JOptionPane.showMessageDialog(this, "Please fill this field");
    jTextField1.requestFocus();
}
else{
    if(!Pattern.matches("[0-9]+", k4))
    {
         JOptionPane.showMessageDialog(this, "Not a valid detail,Enter only numerics");
         jTextField1.requestFocus();
         jTextField1.setText("");
    }
}// TODO add your handling code here:// TODO add your handling code here:
}//GEN-LAST:event_jTextField1FocusLost

    /**
     * @param args the command line arguments
     */
    //
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
