
import javax.swing.JLabel;
import java.sql.*;
import javax.swing.JOptionPane;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * billspare.java
 *
 * Created on Jul 28, 2013, 5:03:49 PM
 */
/**
 *
 * @author DELL
 */
public class billspare extends javax.swing.JFrame {
int i,y;
JLabel []l1=new JLabel[100]; 
	JLabel []l2=new JLabel[100]; 
        JLabel []l3=new JLabel[100]; 
    /** Creates new form billspare */
    public billspare() {
        initComponents();
         try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
  ResultSet rs=con.createStatement().executeQuery("select distinct(customer_name) from regorder_spare");
        while(rs.next()){
            jComboBox1.addItem(rs.getString(1));
         }}catch(Exception ex)  {
             
         }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BILL");
        getContentPane().setLayout(null);

        jLabel1.setText("CUSTOMER NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 43, 101, 24);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(115, 45, 96, 20);

        jLabel2.setText("DATE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(289, 46, 57, 19);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(364, 43, 110, 22);

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("SPARE PARTS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(38, 104, 86, 29);

        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("QTY");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(169, 107, 50, 22);

        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("COST");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(261, 107, 60, 22);

        jLabel7.setText("TOTAL AMOUNT");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 354, 100, 23);

        jLabel8.setText("AMOUNT PAID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 411, 82, 22);

        jLabel9.setText("BALANCE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 475, 71, 23);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(116, 354, 103, 23);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(125, 407, 94, 30);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(125, 475, 94, 30);

        jButton1.setText("PRINT");
        getContentPane().add(jButton1);
        jButton1.setBounds(418, 194, 90, 34);

        jButton2.setText("CANCEL");
        getContentPane().add(jButton2);
        jButton2.setBounds(418, 246, 90, 34);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(752, 0, 64, 67);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\q.png")); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 660, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
ResultSet rs=con.createStatement().executeQuery("select total,date from billspare where name='"+jComboBox1.getSelectedItem()+"'");{
    while(rs.next()){
        jLabel10.setText(rs.getString(1));
        jLabel3.setText(rs.getString(2));
        
    }
}
}catch(Exception ex){
}
try
    {
		Class.forName("com.mysql.jdbc.Driver");
		Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");	
 ResultSet rs=con.createStatement().executeQuery("select spareparts,qty,total_amt from regorder_spare where customer_name='"+jComboBox1.getSelectedItem()+"' and date='"+jLabel3.getText()+"'");
 while(rs.next()){
				
					
					l1[i] = new JLabel();
					l1[i].setText("");
					l1[i].setText(rs.getString(1));
					getContentPane().add(l1[i]);
					l1[i].setBounds(60,y,100,270);
					
					l2[i] = new JLabel();
					l2[i].setText("");
					l2[i].setText(rs.getString(2));
					getContentPane().add(l2[i]);
					l2[i].setBounds(175,y,100,270);
                                        
                                        l3[i] = new JLabel();
					l3[i].setText("");
					l3[i].setText("Rs"+rs.getString(3));
					getContentPane().add(l3[i]);
					l3[i].setBounds(255,y,100,270);
                                        y=y+20;
 }}catch(Exception ex){
 }// TODO add your handling code here:// TO//// TODO add your handling code here:
}//GEN-LAST:event_jComboBox1ActionPerformed

private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
String s1=jTextField1.getText();
int a=Integer.parseInt(s1);
int b=Integer.parseInt(jLabel10.getText());
int c=a-b;
jLabel11.setText(String.valueOf(c));
}//GEN-LAST:event_jTextField1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billspare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billspare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billspare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billspare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new billspare().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
