
import javax.swing.JLabel;
import java.sql.*;
import java.util.Arrays;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * billacc.java
 *
 * Created on Jul 28, 2013, 2:28:03 PM
 */
/**
 *
 * @author DELL
 */
public class billacc extends javax.swing.JFrame {
int i,y;
       
    /** Creates new form billacc */
    public billacc() {
        initComponents();
         try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
  ResultSet rs=con.createStatement().executeQuery("select customer_name from customer_registration");
        while(rs.next()){
            jComboBox1.addItem(rs.getString(1));
         }}catch(Exception ex)  {
             
         }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("CUSTOMER NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 19, 120, 37);

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(120, 30, 125, 20);

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("ACCESSORIES");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(69, 91, 91, 34);

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("QTY");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 96, 77, 24);

        jLabel4.setText("DATE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 30, 66, 26);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(456, 19, 90, 26);

        jLabel6.setText("TOTAL AMOUNT");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 337, 120, 37);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(191, 346, 104, 40);

        jLabel8.setText("AMOUNT PAID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 408, 100, 28);

        jLabel9.setText("BALANCE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 458, 58, 39);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 400, 187, 36);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(191, 458, 187, 33);

        jButton1.setText("PRINT");
        getContentPane().add(jButton1);
        jButton1.setBounds(490, 160, 90, 31);

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(490, 220, 90, 33);

        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("COST");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(287, 94, 84, 29);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\q.png")); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, -70, 600, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

 // TODO add your handling code here:// TO// TODO add your handling code here:
}//GEN-LAST:event_jComboBox1ActionPerformed

private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
String s1=jLabel7.getText();
int a=Integer.parseInt(s1);
String s2=jTextField1.getText();
int b=Integer.parseInt(s2);
int c=b-a;
jLabel10.setText(String.valueOf(c));// TODO add your handling code here:
}//GEN-LAST:event_jTextField1FocusLost

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 int option = JOptionPane.showConfirmDialog (null, "Are u sure u want to exit?");
        //JOptionPane.showConfirmDialog(this, "Are u sure you have chosen right year", "year confirmation", option);
         if(option==JOptionPane.YES_OPTION){
             this.dispose();
         }
         else{
              new billacc().setVisible(true);
         }
             // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
  JLabel []l1=new JLabel[100];
  JLabel []l2=new JLabel[100]; 
  JLabel []l3=new JLabel[100]; 
  
    try{
Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
ResultSet rs=con.createStatement().executeQuery("select total,date from billacc where name='"+jComboBox1.getSelectedItem()+"'");{
    while(rs.next()){
        jLabel7.setText(rs.getString(1));
        jLabel5.setText(rs.getString(2));
    }
}
}catch(Exception ex){
    System.out.println(""+ex);
}
try
    {
		Class.forName("com.mysql.jdbc.Driver");
		Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");	
 ResultSet rs=con.createStatement().executeQuery("select accessories,qty,total_amt from regorder_acc where customer_name='"+jComboBox1.getSelectedItem()+"' and date='"+jLabel5.getText()+"'");
 while(rs.next()){		
					l1[i] = new JLabel();
					l1[i].setText("");
					l1[i].setText(rs.getString(1));
					getContentPane().add(l1[i]);
					l1[i].setBounds(80,y,100,260);
					
					l2[i] = new JLabel();
					l2[i].setText("");
					l2[i].setText(rs.getString(2));
					getContentPane().add(l2[i]);
					l2[i].setBounds(200,y,100,260);
                                        
                                        l3[i] = new JLabel();
					l3[i].setText("");
					l3[i].setText("Rs "+rs.getString(3));
					getContentPane().add(l3[i]);
					l3[i].setBounds(280,y,100,260);
                                        y=y+20;
 }
 }catch(Exception ex){
     System.out.println(""+ex);
 }// TODO add your handling code here:// TO// TODO add your handling code here:
         


         // TODO add your handling code here:
}//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new billacc().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
