import java.awt.Dimension;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * login_id.java
 *
 * Created on Jul 16, 2013, 9:54:33 AM
 */
/**
 *
 * @author DELL
 */
public class login_id extends javax.swing.JFrame {

    /** Creates new form login_id */
    public login_id() {
        setPreferredSize(new Dimension(650,500));
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alter Login Id and Password");
        setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CURRENT USERNAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(22, 82, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CURRENT PASSWORD");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(22, 138, 130, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NEW USERNAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(22, 191, 110, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NEW PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(22, 253, 91, 14);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(212, 79, 140, 30);

        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(212, 130, 140, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(212, 188, 140, 30);

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyTyped(evt);
            }
        });
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(210, 250, 140, 30);

        jButton1.setFont(new java.awt.Font("Segoe Script", 0, 14));
        jButton1.setText("CREATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 345, 130, 31);

        jCheckBox1.setForeground(new java.awt.Color(153, 153, 255));
        jCheckBox1.setText("matched");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(409, 78, 120, 23);

        jCheckBox2.setForeground(new java.awt.Color(153, 153, 255));
        jCheckBox2.setText("matched");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(409, 129, 130, 23);

        jCheckBox3.setForeground(new java.awt.Color(153, 153, 255));
        jCheckBox3.setText("accepted");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(409, 187, 100, 23);

        jCheckBox4.setForeground(new java.awt.Color(153, 153, 255));
        jCheckBox4.setText("accepted");
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(409, 249, 90, 23);

        jCheckBox5.setForeground(new java.awt.Color(153, 153, 255));
        jCheckBox5.setText("not accepted");
        getContentPane().add(jCheckBox5);
        jCheckBox5.setBounds(514, 187, 140, 23);

        jCheckBox6.setForeground(new java.awt.Color(153, 153, 255));
        jCheckBox6.setText("not accepted");
        getContentPane().add(jCheckBox6);
        jCheckBox6.setBounds(514, 249, 130, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\New folder\\bjn.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(409, 318, 61, 66);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel6.setForeground(new java.awt.Color(153, 153, 255));
        jLabel6.setText("CREATE NEW");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 0, 150, 37);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.jpg"))); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(800, 800));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 660, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
String str="";
        try{
          Class.forName("com.mysql.jdbc.Driver");
          Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/car", "root","");
          ResultSet rs=cn.createStatement().executeQuery("select username from login");
          while(rs.next()){
            str=rs.getString(1);
           
          }
         
           if(jTextField1.getText().equals(str)){
             jCheckBox1.setSelected(true);
            }
        }catch(Exception ex){
        }
        
}//GEN-LAST:event_jTextField1KeyTyped

private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
String str="";
        try{
          Class.forName("com.mysql.jdbc.Driver");
          Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/car", "root","");
          ResultSet rs=cn.createStatement().executeQuery("select pwd from login");
          while(rs.next()){
            str=rs.getString(1);
           
          }
         
           if(jPasswordField1.getText().equals(str)){
            jCheckBox2.setSelected(true);
           }
        }catch(Exception ex){
            
        }
            
}//GEN-LAST:event_jPasswordField1KeyTyped

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  if(jCheckBox1.isSelected()&&jCheckBox2.isSelected()){
    try{
          Class.forName("com.mysql.jdbc.Driver");
          Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/car", "root","");
          cn.createStatement().executeUpdate("delete from login");
         cn.createStatement().executeUpdate("insert into login values('"+jTextField2.getText()+"','"+jPasswordField2.getText()+"')");
         JOptionPane.showMessageDialog(this,"Created"); 
         new login().setVisible(true);
          
      }catch(Exception e){
          System.out.print(e);
      }// TODO add your handling code here:
  }
  else{
      JOptionPane.showMessageDialog(this, "You are not authenticated to change the password");
      jTextField1.setText("");
      jTextField2.setText("");
      jPasswordField1.setText("");
      jPasswordField2.setText("");
      
  }
}//GEN-LAST:event_jButton1ActionPerformed

private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
if(jTextField2.getText().length()<=10){
    jCheckBox3.setSelected(true);
    jCheckBox5.setSelected(false);
   
}
else{
    jCheckBox5.setSelected(true);
    jCheckBox3.setSelected(false);
}
    
    // TODO add your handling code here:
}//GEN-LAST:event_jTextField2KeyTyped

private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jPasswordField2ActionPerformed

private void jPasswordField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyTyped
if(jPasswordField2.getText().length()<=10){
    jCheckBox4.setSelected(true);
    jCheckBox6.setSelected(false);
   
}
else{
    jCheckBox6.setSelected(true);
    jCheckBox4.setSelected(false);
}// TODO add your handling code here:
}//GEN-LAST:event_jPasswordField2KeyTyped

private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
String str="";
        try{
          Class.forName("com.mysql.jdbc.Driver");
          Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/car", "root","");
          ResultSet rs=cn.createStatement().executeQuery("select username from login");
          while(rs.next()){
            str=rs.getString(1);
           
          }
         
           if(jTextField1.getText().equals(str)){
             jCheckBox1.setSelected(true);
            }
        }catch(Exception ex){
        }
        
// TODO add your handling code here:
}//GEN-LAST:event_jTextField1FocusLost

private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
String str="";
        try{
          Class.forName("com.mysql.jdbc.Driver");
          Connection cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/car", "root","");
          ResultSet rs=cn.createStatement().executeQuery("select pwd from login");
          while(rs.next()){
            str=rs.getString(1);
           
          }
         
           if(jPasswordField1.getText().equals(str)){
            jCheckBox2.setSelected(true);
           }
        }catch(Exception ex){
            
        }// TODO add your handling code here:
}//GEN-LAST:event_jPasswordField1FocusLost

private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new login_id().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
