
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JCheckBox;

import javax.swing.JPanel;
import javax.swing.JTextField;
import sun.security.jca.JCAUtil;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PLACE_SPARE.java
 *
 * Created on Jul 10, 2013, 4:46:10 PM
 */
/**
 *
 * @author DELL
 */
public class PLACE_SPARE extends javax.swing.JFrame {
Connection con=null;
JPanel p;
JCheckBox[] spareparts;
    int size;
    JTextField[] quant;
    /** Creates new form PLACE_SPARE */
    public PLACE_SPARE() {
        setPreferredSize(new Dimension(600,500));
         p=new JPanel();
  p.setBounds(280,150,300,200);

   p.setLayout(null);
        initComponents();
        try{
        Class.forName("com.mysql.jdbc.Driver");
      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
        ResultSet rs=con.createStatement().executeQuery("select dealer_name from party_registration");
        while(rs.next()){
            jComboBox1.addItem(rs.getString(1));
        }
        ResultSet rs4=con.createStatement().executeQuery("select count(*) from spareparts_reg");
        while(rs4.next()){
                size=rs4.getInt(1);
        }
        spareparts=new JCheckBox[size];
        quant=new JTextField[size];
        }catch(Exception ex){
            System.out.print(ex);
        }
        java.util.Date d=new java.util.Date();
       DateFormat df=new SimpleDateFormat("yyyy/MM/dd");
      jTextField2.setText(df.format(d));
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jCheckBox6.setText("jCheckBox6");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("ORDER FOR SPARE PARTS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 10, 228, 24);

        jLabel2.setText("SELECT DEALER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 141, 14);

        jLabel3.setText("CHOOSE PRODUCTS AND ENTER QTY ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 130, 233, 80);

        jLabel5.setText("DATE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 300, 54, 26);

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(210, 70, 164, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(180, 310, 164, 32);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 370, 107, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(110, 370, 103, 23);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(295, 118, 0, 0);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 660, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 for(int i=0;i<size;i++){
       if(spareparts[i].isSelected()){
    try{
    con.createStatement().executeUpdate("insert into place_spareparts values('"+jComboBox1.getSelectedItem()+"','"+spareparts[i].getText()+"','"+quant[i].getText()+"','"+jTextField2.getText()+"')");
    JOptionPane.showMessageDialog(this, "Order Placed");
    }  catch(Exception e){
    System.out.print(e);
} } } // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCheckBox6ActionPerformed

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
 
        
    
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBox1ActionPerformed

private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
 int x=10,y=10;
 p.removeAll();
 
    JCheckBox m;
    JTextField t;
    try{    
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
             ResultSet rs=con.createStatement().executeQuery("select spare_parts from party_registration where  dealer_name='"+jComboBox1.getSelectedItem()+"'");
              int n=0;
             while(rs.next()&&n<size){
             String st=rs.getString(1);
             m=new JCheckBox(st);
             spareparts[n]=m;
             m.setBounds(x, y, 90, 30);
             t=new JTextField();
             quant[n]=t;
             t.setBounds(x+100,y,70, 30);
             p.add(m);
             p.add(t);
             y=y+50;
             n++;
             }
             add(p);
             revalidate();
             repaint();
        }
        catch(Exception e){
            System.out.print(e);
        }// TODO add your handling code here:
}//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
   //
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
