import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import sun.security.jca.JCAUtil;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PLACE_ACC.java
 *
 * Created on Jul 10, 2013, 4:55:23 PM
 */
/**
 *
 * @author DELL
 */
public class PLACE_ACC extends javax.swing.JFrame {
 Connection con=null;int i;
 JPanel p;
 String st;
  JCheckBox m;
    JTextField t;
    JCheckBox[] myacc;
    int size;
    JTextField[] quant;
     int cost[];
    
    /** Creates new form PLACE_ACC */
    public PLACE_ACC() {
        setPreferredSize(new Dimension(600,500));
         p=new JPanel();
  p.setBounds(280,150,300,200);

   p.setLayout(null);
        initComponents();
        try{
        Class.forName("com.mysql.jdbc.Driver");
      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
        ResultSet rs=con.createStatement().executeQuery("select dealer_name from accdealer_registration");
        while(rs.next()){
            jComboBox1.addItem(rs.getString(1));
        }
        ResultSet rs4=con.createStatement().executeQuery("select count(*) from acc_reg");
        while(rs4.next()){
                size=rs4.getInt(1);
        }
        myacc=new JCheckBox[size];
        quant=new JTextField[size];
        }catch(Exception ex){
            System.out.print(ex);
        }
        
        java.util.Date d=new java.util.Date();
       DateFormat df=new SimpleDateFormat("yyyy/MM/dd");
      jTextField2.setText(df.format(d));
    }
    
             
        
     

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("ORDER FOR ACCESSORIES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 10, 200, 30);

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(240, 90, 157, 20);

        jLabel5.setText("DATE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 340, 70, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 330, 170, 40);

        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 400, 110, 23);

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(70, 400, 120, 23);

        jLabel6.setText("SELECT DEALER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 80, 141, 40);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 50, 620, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
 
}//GEN-LAST:event_jComboBox1ActionPerformed

private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
  int x=10,y=10;
 p.removeAll();
 
   
    try{    
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
             ResultSet rs=con.createStatement().executeQuery("select accessories from accdealer_registration where  dealer_name='"+jComboBox1.getSelectedItem()+"'");
            int n=0;
             while(rs.next()&&n<size){
             String st=rs.getString(1);
             m=new JCheckBox(st);
             myacc[n]=m;
             m.setBounds(x, y, 90, 30);
             t=new JTextField();
             quant[n]=t;
             t.setBounds(x+100,y,70, 30);
             p.add(m);
             p.add(t);
             y=y+50;
             n++;
             }
             add(p);
             revalidate();
             repaint();
        }
        catch(Exception e){
            System.out.print(e);
        }
}//GEN-LAST:event_jComboBox1ItemStateChanged

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  
    try{
 
    for( i=0;i<size;i++){
    
       if(myacc[i].isSelected()){
           
     con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");   
    con.createStatement().executeUpdate("insert into place_acc values('"+jComboBox1.getSelectedItem().toString()+"','"+myacc[i].getText()+"','"+quant[i].getText()+"','"+jTextField2.getText()+")");
    JOptionPane.showMessageDialog(this, "Order Placed");
    } }} catch(Exception e){
    System.out.print(e);
} 
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    //
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
