import java.awt.Color;
import java.awt.Dimension;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegisterOrderacc.java
 *
 * Created on Jul 19, 2013, 2:35:45 PM
 */
/**
 *
 * @author DELL
 */
public class RegisterOrderacc extends javax.swing.JFrame {
    Connection con = null;
    JPanel p;
    String st;
    JCheckBox m;
    JTextField t;
     JCheckBox[] myacc;
     int cost[];
    int size;
    JTextField[] quant;
    ArrayList<String> pro=new ArrayList<String>();
    ArrayList<String> qu=new ArrayList<String>();
    ArrayList<Integer> CO=new ArrayList<Integer>();

    /** Creates new form RegisterOrderacc */
    public RegisterOrderacc() {
     
        setPreferredSize(new Dimension(600,600));
         /*adding component to panel*/
          p=new JPanel();
         p.setBounds(80,200,500,200);
         p.setLayout(null);
      
         initComponents();
         try{
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
        ResultSet rs=con.createStatement().executeQuery("select customer_name from customer_registration");
        while(rs.next()){
            jComboBox1.addItem(rs.getString(1));
        }
        ResultSet rs4=con.createStatement().executeQuery("select count(*) from acc_reg");
        while(rs4.next()){
                size=rs4.getInt(1);
        }
        myacc=new JCheckBox[size];
        cost=new int[size];
        quant=new JTextField[size];
        }catch(Exception ex){
            System.out.print(ex);
        }
          java.util.Date d=new java.util.Date();
       DateFormat df=new SimpleDateFormat("yyyy/MM/dd");
      jTextField1.setText(df.format(d));
        int x=10,y=10;
    try{    
         Class.forName("com.mysql.jdbc.Driver");
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
             ResultSet rs=con.createStatement().executeQuery("select accessories,cost from acc_reg");
            int n=0;
             while(rs.next()&&n<size){
             System.out.print(rs.getString(1));
             st=rs.getString(1);
             m=new JCheckBox(st);
             myacc[n]=m;
             cost[n]=Integer.parseInt(rs.getString(2));
             m.setBounds(x, y, 250, 30);
             t=new JTextField();
             quant[n]=t;
             t.setBounds(x+200,y,270, 30);
             p.add(m);
             p.add(t);
             y=y+50;
             n++;
             }
             jLabel5.add(p);
            
             
             p.repaint();
             p.revalidate();
             repaint();
             revalidate();
        }
        catch(Exception e){
            System.out.print(e);
        }
         /*panel end*/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ORDER");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("REGISTER ORDER FOR ACCESSORIES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(183, 11, 290, 37);

        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("CUSTOMER NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 104, 31);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(150, 80, 126, 20);

        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("CHOOSE ACCESSORIES AND ENTER QUANTITY");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 160, 292, 43);

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("DATE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 383, 45, 27);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 380, 136, 33);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 460, 88, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 460, 100, 23);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 590, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int sum=0;int tempcost;
    for(int i=0;i<size;i++){
    
       if(myacc[i].isSelected()){
           pro.add(myacc[i].getText());
           qu.add(quant[i].getText());
          tempcost=Integer.parseInt(quant[i].getText())*cost[i]; 
            CO.add(tempcost);
        sum=sum+tempcost; 
        System.out.print(sum);
    try{
    con.createStatement().executeUpdate("insert into regorder_acc values('"+jComboBox1.getSelectedItem()+"','"+myacc[i].getText()+"','"+tempcost+"','"+jTextField1.getText()+"','"+quant[i].getText()+"')");  
    }  catch(Exception e){
    System.out.print(e);
} } }
 JOptionPane.showMessageDialog(this, "Order Registered & total amount is RS. "+sum);
 try{
    con.createStatement().executeUpdate("insert into billacc values('"+jComboBox1.getSelectedItem()+"','"+sum+"','"+jTextField1.getText()+"')");  
    }  catch(Exception e){ 
        System.out.println(""+e);
            }
 String st="";
   
 new Bill_generation(String.valueOf(jComboBox1.getSelectedItem()),pro,qu,CO,sum,jTextField1.getText(),st).setVisible(true);
    System.out.println("deep");
}//GEN-LAST:event_jButton1ActionPerformed

private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();// TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterOrderacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterOrderacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterOrderacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterOrderacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new RegisterOrderacc().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
