import java.awt.Color;
import java.awt.Dimension;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * REGISTERORDERSPARE.java
 *
 * Created on Jul 18, 2013, 9:38:35 AM
 */
/**
 *
 * @author DELL
 */
public class REGISTERORDERSPARE extends javax.swing.JFrame {
Connection con = null;
int sum=0;
    JPanel p;
    String st;
    JCheckBox m;
    JTextField t;
     JCheckBox[] myacc;
     int cost[];
    int size;
    JTextField[] quant;
   
    ArrayList<String> pro=new ArrayList<String>();
    ArrayList<String> qu=new ArrayList<String>();
    ArrayList<Integer> CO=new ArrayList<Integer>();

    
    /** Creates new form REGISTERORDERSPARE */
    public REGISTERORDERSPARE() {
         setPreferredSize(new Dimension(600,600));
         /*adding component to panel*/
          p=new JPanel();
       
         p.setBounds(80,200,300,200);
         
         p.setLayout(null);
        
         initComponents();
         try{
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
        ResultSet rs=con.createStatement().executeQuery("select customer_name from customer_registration");
        while(rs.next()){
            jComboBox2.addItem(rs.getString(1));
        }
        ResultSet rs4=con.createStatement().executeQuery("select count(*) from spareparts_reg");
        while(rs4.next()){
                size=rs4.getInt(1);
        }
        myacc=new JCheckBox[size];
        cost=new int[size];
        quant=new JTextField[size];
        }catch(Exception ex){
            System.out.print(ex);
        }
          java.util.Date d=new java.util.Date();
       DateFormat df=new SimpleDateFormat("yyyy/MM/dd");
      jTextField2.setText(df.format(d));
        int x=10,y=10;
    try{    
         Class.forName("com.mysql.jdbc.Driver");
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
             ResultSet rs=con.createStatement().executeQuery("select spare_parts,cost from spareparts_reg");
            int n=0;
             while(rs.next()&&n<size){
             System.out.print(rs.getString(1));
             st=rs.getString(1);
             m=new JCheckBox(st);
             myacc[n]=m;
             cost[n]=Integer.parseInt(rs.getString(2));
             m.setBounds(x, y, 150, 30);
             t=new JTextField();
             quant[n]=t;
             t.setBounds(x+100,y,170, 30);
             p.add(m);
             p.add(t);
             y=y+50;
             n++;
         }
             jLabel3.add(p);
             
             p.repaint();
             p.revalidate();
             revalidate();
             repaint();
        }
        catch(Exception e){
            System.out.print(e);
        }
    
         /*panel end*/
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CUSTOMER NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 29, 114, 14);

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(228, 29, 120, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SPARE PARTS ORDERED");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 90, 170, 43);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 330, 70, 14);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(230, 310, 140, 30);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 400, 80, 23);

        jButton2.setText("CANCEL");
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 400, 80, 23);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -60, 580, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
 // TODO add your handling code here:
}//GEN-LAST:event_jComboBox2ItemStateChanged

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 int tempcost;
    for(int i=0;i<size;i++){
    
       if(myacc[i].isSelected()){
          pro.add(myacc[i].getText());
           qu.add(quant[i].getText());
          tempcost=Integer.parseInt(quant[i].getText())*cost[i]; 
            CO.add(tempcost);
        sum=sum+tempcost; 
    try{
    con.createStatement().executeUpdate("insert into regorder_spare values('"+jComboBox2.getSelectedItem()+"','"+myacc[i].getText()+"','"+tempcost+"','"+jTextField2.getText()+"','"+quant[i].getText()+"')");  
    }  catch(Exception e){
    System.out.print(e);
} } } // TODO add your handling code here:

    JOptionPane.showMessageDialog(this, "Order Registered & total amount is RS. "+sum);
      try{
    con.createStatement().executeUpdate("insert into billspare values('"+jComboBox2.getSelectedItem()+"','"+sum+"','"+jTextField2.getText()+"')");  
    new Bill_generation(jComboBox2.getSelectedItem().toString(), pro, qu, CO, sum,jTextField2.getText(),st).setVisible(true);
      }  catch(Exception e){ 
            }
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTERORDERSPARE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTERORDERSPARE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTERORDERSPARE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTERORDERSPARE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new REGISTERORDERSPARE().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
