
import java.awt.Dimension;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * salaryatt.java
 *
 * Created on Jul 25, 2013, 12:04:21 PM
 */
/**
 *
 * @author DELL
 */
public class salaryatt extends javax.swing.JFrame {
Connection con=null;

    /** Creates new form salaryatt */
    public salaryatt() {
        setPreferredSize(new Dimension(400,380));
        initComponents();
        try{
        Class.forName("com.mysql.jdbc.Driver");

 Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
        ResultSet rs=con.createStatement().executeQuery("select name from employee_registration");
        while(rs.next()){
            jComboBox1.addItem(rs.getString(1));
        }}catch(Exception ex){
           
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EMPLOYEE NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 40, 105, 30);

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(241, 45, 124, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ATTENDENCE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 120, 85, 34);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(241, 126, 124, 34);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 210, 124, 34);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SALARY PER DAY");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 210, 110, 30);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(257, 336, 194, 37);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\images (17).jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -50, 600, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
try{
     Class.forName("com.mysql.jdbc.Driver");

  con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
 ResultSet rs=con.createStatement().executeQuery("select count("+jComboBox1.getSelectedItem()+") from attendence where "+jComboBox1.getSelectedItem()+"='present'");
 while(rs.next())
 {
     jLabel5.setText(rs.getString(1));
     
 }}catch(Exception ex){
      System.out.print(ex);
 
     
 }
try{
     Class.forName("com.mysql.jdbc.Driver");

  con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
 ResultSet rs=con.createStatement().executeQuery("select salary from employee_registration where name='"+jComboBox1.getSelectedItem()+"'"); 
 while(rs.next()){
     jLabel6.setText(rs.getString(1));
     
 }
}catch(Exception ex){
     System.out.print(ex);
           

    


}


  // TODO add your handling code here:
}//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line argum
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salaryatt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salaryatt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salaryatt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salaryatt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new salaryatt().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
