import java.awt.Dimension;
import java.sql.*;


/*
 * yearlyacc.java
 *
 * Created on Sep 21, 2013, 9:17:12 PM
 */
/**
 *
 * @author DELL
 */
public class yearlyacc extends javax.swing.JFrame {
 java.util.Date d=new java.util.Date();
String h="";
             
           
            public yearlyacc(){
                setPreferredSize(new Dimension(400,360));
    
        initComponents();
        for(int i=1;i<13;i++)
        {
            jComboBox1.addItem(i);
        }
        int cost=0;
         jTextField2.setText("");
 try{
 Class.forName("com.mysql.jdbc.Driver");
 Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
 ResultSet rs=con.createStatement().executeQuery("select distinct(date) from regorder_acc"); 
while(rs.next())
{
    d=rs.getDate(1);
    System.out.println(""+rs.getDate(1));
    jComboBox2.addItem(d.getYear()+1900);
    jComboBox3.addItem(d.getYear()+1900);
}   

 }
catch(Exception e)
{
 System.out.println(e);
 
 } 


       
       
    }
    /** Creates new form yearlyacc */
    
 
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("MONTH");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(18, 38, 63, 22);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(85, 39, 110, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("YEAR");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(222, 42, 47, 14);

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(273, 39, 109, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(129, 139, 165, 43);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("YEARLY INCOME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(95, 229, 120, 20);

        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(231, 226, 110, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(157, 282, 126, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\PageBackgroundChurch-1140x632.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 510, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
   
}//GEN-LAST:event_jComboBox1ActionPerformed

private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged

        // TODO add your handling code here:
}//GEN-LAST:event_jComboBox2ItemStateChanged

private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
int cost=0;
         jTextField1.setText("");
 try{
 Class.forName("com.mysql.jdbc.Driver");
 Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
 ResultSet rs=con.createStatement().executeQuery("select date,total_amt from regorder_acc"); 
while(rs.next())
{
    d=rs.getDate(1);
   if(jComboBox1.getSelectedItem().equals(d.getMonth()+1)&&jComboBox2.getSelectedItem().equals(d.getYear()+1900))
  {
      System.out.print("inside if");
      cost=cost+Integer.parseInt(rs.getString(2));
  }
}
    
jTextField1.setText(String.valueOf(cost));
 }
catch(Exception e)
{
 System.out.println(e);
}                       
}//GEN-LAST:event_jComboBox2ActionPerformed

private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
 
}//GEN-LAST:event_jComboBox3ItemStateChanged

private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
int cost=0;
         jTextField2.setText("");
 try{
 Class.forName("com.mysql.jdbc.Driver");
 Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","");
 ResultSet rs=con.createStatement().executeQuery("select distinct(date),total_amt from regorder_acc"); 
while(rs.next())
{
    d=rs.getDate(1);
    if(jComboBox3.getSelectedItem().equals(d.getYear()+1900))
  {
      
      cost=cost+Integer.parseInt(rs.getString(2));
     
  }
}
    
jTextField2.setText(String.valueOf(cost));
 }
catch(Exception e)
{
 System.out.println(e);
 
 } 
 // TODO add your handling code here// TODO add your handling code here:
}//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yearlyacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yearlyacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yearlyacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yearlyacc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new yearlyacc().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
